### ISSUE TITLE
Archipelago fails when not in a if __name__ == "__main__" block

### ISSUE THREAD

**Issue by lsangild** [esa/pagmo2#130]
I am trying to apply archipelago to a problem of mine, but it seems it is not possible to do with any user defined problem, except for the prepackaged ones on [https://esa.github.io/pagmo2/docs/python/problems/py_problems.html](url).
When running the code below (and my own problem, and other problems not in the above list), I get the errors shown in  [ArchipelagoError.txt](https://github.com/esa/pagmo2/files/1302986/ArchipelagoError.txt) and I am not able to solve them myselves.
Could this be due to the "thread safety" of my problems? I have not been able to change them from "None" to "Basic".

```
import pygmo as pg

class sphere_function:
        def __init__(self, dim):
            self.dim = dim
   
        def fitness(self, x):
            return [sum(x*x)]
   
        def get_bounds(self):
            return ([-1] * self.dim, [1] * self.dim)
   
        def get_name(self):
            return "Sphere Function"
   
        def get_extra_info(self):
            return "\tDimensions: " + str(self.dim)

prob = pg.problem(sphere_function(3))
algo = pg.algorithm(pg.bee_colony(gen = 20, limit = 20))
archi = pg.archipelago(n=1, algo=algo, prob=prob, pop_size=10)
```

**Comment by lsangild** [comment]
I failed to mention that I am running pygmo 2.4 on Python 3.6.2 64-bit through Anaconda on Windows 10.

**Comment by darioizzo** [comment]
Your code is valid and works in our installation. 
Maybe you have some installation problems?

**Comment by lsangild** [comment]
I am uncertain if it was prepackaged with my Anaconda install or if installed using `conda install pygmo`.
`conda list` shows
pygmo                     2.4                 np112py36_0    conda-forge

**Comment by bluescarni** [comment]
@lsangild Can you try to put the last three lines in a main block? Something like this:

```python
if __name__ == "__main__":
    prob = pg.problem(sphere_function(3))
    algo = pg.algorithm(pg.bee_colony(gen = 20, limit = 20))
    archi = pg.archipelago(n=1, algo=algo, prob=prob, pop_size=10)
```

**Comment by lsangild** [comment]
@bluescarni That worked!
Actually I only need to put the archipelago line in a main block.
Can you elaborate on the cause of the issue?

**Comment by bluescarni** [comment]
@lsangild The first instantiation of an island/archipelago triggers the creation of a pool of processes that do the actual parallel optimisation work when you call ``evolve()``. These processes need to ``import`` your script in order to "see" the definition of your problem, but if in the import phase of your script you are creating an archipelago then this recursively triggers the creation of another pool of processes, which again will try to import your script, triggering the creation of an archipelago, etc. etc.

See also the first two answers here:

https://stackoverflow.com/questions/20360686/compulsory-usage-of-if-name-main-in-windows-while-using-multiprocessi

For pygmo, it means in practice that you should not create islands/archipelagos as part of the module code (i.e., the code that gets executed upon importing the module).

**Comment by darioizzo** [comment]
I renamed the issue for future references.
Can we close this?

**Comment by lsangild** [comment]
Thank you for your help :+1:
