### ISSUE TITLE
Constrained multi-objective optimization

### ISSUE THREAD

**Issue by smnsierra** [esa/pagmo2#131]
Hello,
first of all let me thank you for the work you put into this project and for making it available to the world.
I am tryng to solve a constrained multi-objective problem, but i don't seem to find a way to implement constraints in this last version. I read the documentation of PyGM0 1.xx and there is a section with tutorials on constraint handling. Do those methods apply for the 2.5 version as well? Or else can you provide some pointers to help me do this?
Thank you in advance for your support.

Regards,
Simone.

**Comment by darioizzo** [comment]
Some tutorials can be found here: https://esa.github.io/pagmo2/docs/python/tutorials/python_tut.html, see the one on coding a UDP with constraints

**Comment by smnsierra** [comment]
Thank you for you quick reply, I read that tutorial but it's about a sigle-objective optimization problem. Can you provide additional resources for constrained multi-objective optimization? I apologize if my question might seem trivial, but this is my first attempt in trying to solve this kind of problems.

**Comment by darioizzo** [comment]
Please next time post your requests on the gitter chat (https://gitter.im/pagmo2/Lobby) so that other user may help.

To code a UDP that is multiobjective and constrained you just need to implement the methods get_nobj() and get_nec(), get_nic() (obj n., equality const. n. and inequality const. n. see documentation).

To solve it its on you to come up with a solution strategy. No algorithm can tackle these problems in general. 

One option is to transform the problem decomposing it ...
