### ISSUE TITLE
pygmo parallel evauation of `problem.fitness` for algorithm.

### ISSUE THREAD

**Issue by costrouc** [esa/pagmo2#143]
I have a problem where I call a remote server to asynchronously evaluate `problem.fitness` since it is a fairly expensive task. This means that I should be able to evaluate the entire population in parallel within a single process. Is this possible in pygmo? Or is there a recommended way to do this. I know that islands implement parallel processing but that only parallelizes multiple `algorithm.evolve(population)` calls.

From what I have been reading all `program` and `algorithm` instances return `pygmo.thread_safety.none` which makes this a no go. Is this true?

Each call to `problem.fitness` takes about 20 ms to evaluate. So I would like to evaluate the population concurrently so I can increase the number of evaluations / second.

**Comment by costrouc** [comment]
Looking at the c++ implementations of each algorithm it doesn't look like it is possible to evaluate the population in parallel. Are there any downsides to having small populations say 10 - 20?

**Comment by darioizzo** [comment]
The parallel evaluation of single fitness evaluation is not something currently offered in pagmo. We have discussed it in several development meetings, but so far we are not planning anything.

Eventually we might offer a parallel population factory, but the core of the parallelization will remain coarse grained.

**Comment by willcodeforfudd** [comment]
Is this the right place to bump this discussion?  I am using pygmo, and I have a project where my function implementations take around an hour.  To run any kind of fair test I'll have to do some kind of comparison with a standard algorithm like moea/d, cpus aren't a problem, but time is.

I'll check out the code in the next few days and see if I can lash something together.  I could just parallelise the fitness calls, then loop/sleep till all the fitness calls complete per generation?  I just thought I'd check in with what has been discussed in case there is a plan in the works...

**Comment by bluescarni** [comment]
@willcodeforfudd are you referring to the parallel initialisation of a population/island/archipelago? This is in the works, see #226.

Or do you have something else in mind?

**Comment by willcodeforfudd** [comment]
It looks like this is exactly like what I was hoping for.  I'll check it out in a bit more detail tomorrow.  I use an external program for the fitness, so I just want to fork/new-thread all of the fitness evaluations onto different cpus (I have access to a pretty good cluster).

I haven't fully understood the code fully yet, but I'd much rather stick to your thought-out framework.  What is the trick to making fitness parallel?  I suppose I'd look into making sure that the UDP is capable of calling the fitness evaluations asynchronously in 'evolve' then checking if it has got all the results?  I don't mind if evolve blocks at every generation.   I've been using the MOEA/D so far,  so I'll probably look at using that.

Any other pointers to picking up the pagmo2 code?  I've been using pygmo, and my C++ is a bit rusty, would be great to share something back to the community!  So let me know if there's work needing done that would help me get going but has been too dull.

**Comment by bluescarni** [comment]
Let me re-iterate that in #226 we will implement parallelization only for the *initialisation* of a population/island/archipelago. Individual algorithms (at least those which are implemented in pagmo right now) run fitness evaluations in serial mode, the parallelization happens at a higher level (i.e., you are running multiple optimisations in parallel in multiple threads or processes).

Nothing prevents users to implement algorithms that invoke the ``fitness()``of a problem in parallel *within* a single ``evolve()`` call (and in fact the modifications in #226 will allow users to query the thread safety level of a problem's fitness to a finer degree, so that an hypothetical parallel algorithm can refuse to operate if a problem is not thread-safe enough). But no algorithm currently implemented in pagmo does that - perhaps @darioizzo can comment in general on the topic of algorithms parallelised in this fine-grained way.

As to how the fitness is parallelised, it depends on the thread safety level of the problem. On the C++ side, for the first implementation of parallel init we will support initially only multi threading via the TBB library. Later, we will enable fork-based and MPI-based parallel initialisation as well. On the Python side, we will use multi-threading for problems implemented in C++, and otherwise multi-processing and ipyparallel-based clustering.

**Comment by bluescarni** [comment]
On the topic of contributions to pagmo2, they are always welcome!

The API is fully documented in both C++ and Python, but unfortunately we don't have any high-level design document so I think it might be a bit overwhelming to start contributing initially. You are encouraged to join the chat channel to discuss potential contributions, and in order to have a low-latency feedback loop with the devs:

https://gitter.im/pagmo2/Lobby

An easy way to start contributing is with improvements to documentation/tutorials. We are also always looking for better/new algorithms, so new original implementation  of existing algorithms or wrappers for existing implementations are also very much welcome.

**Comment by willcodeforfudd** [comment]
Thanks for your help.  Looking at it,  I agree that the easiest solution for me is to just modify moead (my problem is MO so there is only moead and harmony search).  Perhaps I can just change a few lines around 236 of moead.hpp?

  If I switch it to call all of the fitnesses then wait for results from all of them before processing?  Its a poor-man's parallel code, but my fitness algorithm calls bash code, and takes ~1hour, so I don't mind the overhead of external calls or file I/O.  I'll have to add another function to my problem interface ("collect_fitness"(?))  and I don't mind if the code blocks at any collect_fitness since I need all of the population to be evaluated before I proceed?

**Comment by willcodeforfudd** [comment]
Thanks for your help.  Looking at it,  I agree that the easiest solution for me is to just modify moead (my problem is MO so there is only moead and harmony search).  Perhaps I can just change a few lines around 236 of moead.hpp?

  If I switch it to call all of the fitnesses then wait for results from all of them before processing?  Its a poor-man's parallel code, but my fitness algorithm calls bash code, and takes ~1hour, so I don't mind the overhead of external calls or file I/O.  I'll have to add another function to my problem interface ("collect_fitness"(?))  and I don't mind if the code blocks at any collect_fitness since I need all of the population to be evaluated before I proceed?
