### ISSUE TITLE
CI weaknesses

### ISSUE THREAD

**Issue by darioizzo** [esa/pagmo2#163]
From several conversations with @bluescarni some todos emerged for our CI
- [ ] Enable nbsphinx extension. Problematic as the python36 build making the docs seem to fail if nbsphinx is enabled. Maybe a strange interaction between pip and conda installed packages?
- [x] ipyparallel 6.1 seems to be problematic in conda. solve the issue upstream or pin everything to <6.1?
- [x] remove the workaround that makes use of old travis images that are compatible with conda binaries (anvil images activated via the ```sudo: required```
- [ ] maybe introduce the use of docker container to speed up compilation and give more stability to the CI

**Comment by bluescarni** [comment]
CI robustness is now being improved in #266.

**Comment by bluescarni** [comment]
I am gonna go ahead and close this report for the time being, as, thanks to the library work and the adoption of circleci, the situation has improved markedly. There are still some issue, e.g, we are now bottlenecked by the appveyor builds because they are not parallel. In the future we should probably consider switching over to the Azure CI pipeline for Windows builds.
