### ISSUE TITLE
Is there an equivalent of the _compare_fitness_impl() method found in pagmo1?

### ISSUE THREAD

**Issue by KishManani** [esa/pagmo2#179]
_compare_fitness_impl() was very useful in user defined problems, in particular for multi-objective optimisation. Does a similar function exist in pagmo2? Thanks.

**Comment by darioizzo** [comment]
We decided to not provide that machinery in pagmo2 as it obscured greatly the actual behaviour of  various optimizers.

 In pagmo2 you can implement the fitness comparison logic directly in your UDA (user defined algorthm), otherwise pagmo's UDAs (nsga2 moad etc..) are using internally the various sorting utility functions also provided in the code base (https://esa.github.io/pagmo2/docs/python/utils/py_mo_utils.html)

Let us know if you think your particular case would require some ad hoc utility or change in the current API, we are always available to discuss woth user on this. 

Also, please use our gitter channel for these type of discussions (https://gitter.im/pagmo2/Lobby)
