### ISSUE TITLE
Tracking evolution for nlopt?

### ISSUE THREAD

**Issue by emmae0** [esa/pagmo2#180]
Hello,

I am using nlopt. I know that algo.extract(pg.nlopt).get_log() gives you a log with the fitness evaluations made, but is there anywhere I can find the input values (aka the x values) evaluated to find those fitness evaluations?

Thanks!

**Comment by darioizzo** [comment]
i am afraid not .... not sure whether the nlopt library stores those values
at all ...

**Comment by bluescarni** [comment]
I have added to pygmo a decorator meta-problem, that allows you (amongst other things) to modify a problem so that it logs the decision vectors that have been passed to it. See for instance the example in the documentation:

https://esa.github.io/pagmo2/docs/python/tutorials/udp_meta_decorator.html#logging-fitness-evaluations

This should allow you to log the information you need (not only with nlopt, but with any other algorithm).

I am closing the report for now, please open a new one if you find issues with the decorator problem approach.
