### ISSUE TITLE
When using Cobyla to polish the solution, champion_f does not necesseraly return best design

### ISSUE THREAD

**Issue by NKlinke** [esa/pagmo2#184]
Hi,

i am using SADE for global optimization and want to polish the best individual found with local optimization. 

```
algo = pg.algorithm(pg.cstrs_self_adaptive(iters=30, algo=pg.sade(gen=30)))
algo.set_verbosity(1)
pop = algo.evolve(pop)

algo = pg.algorithm(pg.nlopt("cobyla"))
algo.set_verbosity(1)
pop = algo.evolve(pop)
```

The optimization itself works as it should but when I want to inpect the result, I can find a better result in the log of cobyla than reported by the population (e.g. pop.get_f)

Output from pop.get_f
```
  [Terminal] ('f', array([ 56.06120539,   1.8418838 ,   0.81490053,   1.68429062,
  [Terminal]          1.8418838 , 126.28604134, 108.15027019,   0.44078239,
  [Terminal]          0.49965481,   0.26844253]))
```

Last four lines from cobyla 
```
      1076        51.9232              0              0
      1077        51.9238              1   1.33925e-010 i
      1078        51.9244              1   4.55191e-015 i
      1079        51.9234              1    5.9952e-015 i
```

For me it seems that pygmo is checking of cobyla is returning a solution with zero constraint violation; if not, the returned solutions is rejected. It would be preferable to the best solution from cobyla history or a variable constraint tolerance level. 

Kind Regards
Niklas

**Comment by bluescarni** [comment]
The behaviour here should depend on the constraints tolerance setting of your problem:

https://esa.github.io/pagmo2/docs/python/py_problem.html#pygmo.problem.c_tol

What pagmo does is to pass this tolerance setting down to the NLOPT call, so that NLOPT's and pagmo's notions of a satisfied constraint should coincide. ``c_tol`` is set to a vector of zeroes on startup.

Can you try to relax ``c_tol`` a bit and see what happens?

**Comment by darioizzo** [comment]
Note that you can set the tolerance also from a  scalar value (undocumented).

```
prob.c_tol = 1e-8
```
is allowed.
You can check the problem tolerance retreiving the property or from the screen output

```
print(prob)
```

**Comment by darioizzo** [comment]
Actually not, sorry. Ignore the message above, that overload is only available in c++.

**Comment by bluescarni** [comment]
Setting the ``c_tol`` via a scalar has been implemented in #185.

**Comment by NKlinke** [comment]
Hey guys, 

thanks for implementing the ability to overwrite the constraint tolerance value. When using a reasonable value (like 1e-8), the behaviour is as it should be. 

Nevertheless I think the underlying behaviour remains unchanged. When the latest iteration of NLOpt has a constraint violation, pop.get_f is returning the start value, even if a solution with zero constraint violation was evaluated down the way. But I guess, this depends on the implementaton of NLOpt itself?

**Comment by bluescarni** [comment]
You are right: as far as pagmo is concerned, the nlopt algorithm is a black box over which we don't have any control (apart from setting a variety of parameters for the optimisation run). Once we call into the nlopt api to start the optimisation, there's little we can do apart from stopping it.

Something that might help you would be to change the implementation of your UDP so that the fitness function records somewhere (i.e., in the UDP object itself) all the decision vectors that are passed to it (and perhaps even their associated fitness values/constraints violations). You can then examine this list of decision vectors and possibly find out if there are "interesting" vectors that were generated by nlopt's optimisation routine.

**Comment by NKlinke** [comment]
nice workaround. Thanks!

**Comment by NKlinke** [comment]
As far as the documentation is stating, I can you a decorator problem from 2.9 on. Since the latest release is 2.8, is there a clever way of logging here? I tried to add a variable into the UPD, but a cannot access it from the outside.

**Comment by bluescarni** [comment]
You can extract the UDP instance from the ``problem`` object with the ``extract()`` method. That should allow you to reach the variable in the UDP. Something like this:

```ipython
In [1]: import pygmo as pg

In [2]: class prob:
   ...:     def __init__(self):
   ...:         self._n = 0
   ...:     def fitness(self, x):
   ...:         self._n = self._n + 1
   ...:         return x
   ...:     def get_bounds(self):
   ...:         return ([0],[1])
   ...:     

In [3]: p = pg.problem(prob())

In [4]: p.extract(prob)._n
Out[4]: 0

In [5]:
```

If you have full control on the definition of the UDP, it's not strictly necessary to use the decorator problem, as you can just manually change the definition of your fitness function. The decorator is more about changing existing problems in a non-intrusive way (but of course you can also use it in this instance, if you prefer).

**Comment by NKlinke** [comment]
Thank you very much.

**Comment by NKlinke** [comment]
Sorry to bother you again, but with python 2.7 in Windows (installed via pip) the extract returns a TypeError: 

``` 
>>> import pygmo as pg
>>> class prob:
...      def __init__(self):
...          self._n = 0
...      def fitness(self, x):
...          self._n = self._n + 1
...          return x
...      def get_bounds(self):
...          return ([0],[1])
...
>>> p = pg.problem(prob())
>>> p.extract(prob)._n
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\TRB_CAE\Python\Miniconda3\envs\py27_d\lib\site-packages\pygmo\_patch_problem.py", line 54, in _problem_ext
ract
    raise TypeError("the 't' parameter must be a type")
TypeError: the 't' parameter must be a type
```

**Comment by bluescarni** [comment]
I think in Python 2.7 you have to derive from ``object`` for this to work, so it should be

```python
class prob(object):
```

rather than just

```python
class prob:
```

I think this has to do with the difference between old-style and new-style classes:

https://wiki.python.org/moin/NewClassVsClassicClass

(In Python 3 all classes are new style by default)

Let us know if this fixes the issue for you.

**Comment by NKlinke** [comment]
This was my mistake. Works perfect now. Thanks again!

**Comment by bluescarni** [comment]
No problem!

Actually I had not realized before that this issue with ``extract()`` could arise in Python 2, so I have just added a general disclaimer in the documentation about Python 2 vs 3 issues in the documentation and in the examples (we are always assuming Python 3 syntax in the docs).
