### ISSUE TITLE
Wheel for Python 3.7 on Windows

### ISSUE THREAD

**Issue by jetuk** [esa/pagmo2#246]
There's no wheel for Python 3.7 on Windows uploaded to pypi. There is one for 3.7 & Linux however.

**Comment by darioizzo** [comment]
@jetuk Yes, you are right for py37 in windows we recommend to usa conda (win py37 packages are available there for pygmo). We are also considering to not give support to pip anymore in the future.

We may change our minds if we manage to get rid of boost in favour of  pybind11 ....

**Comment by bluescarni** [comment]
@jetuk To expand on what @darioizzo said...

The windows pip wheels are currently built using the MinGW compiler toolchain. We are using MinGW rather than MSVC because this allows us to easily build wheels for Python 2.7 and also to enable support for optional pagmo dependencies requiring a Fortran compiler (microsoft does not provide a Fortran compiler in Visual Studio, but MinGW does).

However, Python for Windows is not really MinGW friendly, and in the past we had to go through a complex procedure to patch both the Python headers and the Boost Python library to work correctly on MinGW. Once you know how to do it, it's not a complex task, but it is rather time consuming, it requires a Windows virtual machine, and it varies slightly with different Python versions.

Unfortunately, we have no manpower at this time to repeat this whole procedure for new Python versions, so for the foreseeable future pip on Windows will remain stuck on Python 3.6.

Of course, if anyone from the community wants to take up the mantle, we would be willing and able to provide step-by-step guidance.

**Comment by stonebig** [comment]
windows is not a python-2.7 shop anymore.
