### ISSUE TITLE
NSGA-II C++ example

### ISSUE THREAD

**Issue by MLopez-Ibanez** [esa/pagmo2#256]
Hi,

I'm trying to use C++ pagmo for multi-objective optimization. I can compile the single-objective example in the tutorial but I cannot compile a multi-objective one. This is what I tried:

```c++
#include <iostream>

#include <pagmo/algorithm.hpp>
#include <pagmo/algorithms/nsga2.hpp>
#include <pagmo/archipelago.hpp>
#include <pagmo/problem.hpp>
#include <pagmo/problems/dtlz.hpp>

using namespace pagmo;

int main()
{
    // 1 - Instantiate a pagmo problem constructing it from a UDP
    // (user defined problem).
    problem prob{dtlz(1, 10, 2)};

    // 2 - Instantiate a pagmo algorithm
    algorithm algo{nsga2(100)};

    // 3 - Instantiate an archipelago with 16 islands having each 20 individuals
    //archipelago archi{16, algo, prob, 20};

    // 4 - Run the evolution in parallel on the 16 separate islands 10 times.
    algo.evolve(10);

    // 5 - Wait for the evolutions to be finished
    algo.wait_check();

    // 6 - Print the fitness of the best solution in each island
    for (const auto &isl : algo) {
        for (const auto &sol : isl.get_population().get_f()) {
            std::cout << sol[0] << ' ' << sol[1] << '\n';
        }
    }
}
```

but it doesn't even compile. What am I doing wrong? It would be very helpful to have a MO example in the tutorial

Thanks,

Manuel.

**Comment by bluescarni** [comment]
I'd suggest you to post the compiler error message next time, as that is needed in order to diagnose any compilation problem.

In this case, it seems you are mixing up the ``algorithm`` and ``archipelago`` APIs: the ``wait_check()`` does not exist in the ``algorithm`` class, only in the ``archipelago`` class. I *think* that uncommenting the archipelago construction line and then replacing ``algo`` with ``archi`` may be enough to get the example compiling.

**Comment by darioizzo** [comment]
I think there are more mistakes than those correctly pointed out by @bluescarni 
```
int main()
{
    // 1 - Instantiate a pagmo problem constructing it from a UDP
    // (user defined problem).
    problem prob{dtlz(1, 10, 2)};

    // 2 - Instantiate a pagmo algorithm
    algorithm algo{nsga2(100)};

    // 3 - Instantiate a population
    population pop{prob, 24};

    // 4 - Run the evolution in parallel on the 16 separate islands 10 times.
    pop = algo.evolve(pop);

   // 5 - Get the best (need pagmo/io.hpp header)
  print(pop.champion_f)
}
```
This (untested) is the intended use without and archi

**Comment by MLopez-Ibanez** [comment]
Dario, thanks! 

This compiles and runs without problem. It would really be useful to have such an example in the tutorial or docs. It seems the interface is somewhat different from the example there. I would have never found that one has to instantiate a population and assign the return value of algo.evolve.

Is this a good way to ask for help? We are starting a new research project and we are considering to extend Pagmo2, but we find the documentation a bit too sparse.

Best,

Manuel.

**Comment by MLopez-Ibanez** [comment]
A complete example that compiles without warnings and runs. This could be useful for the documentation:

```c++
#include <pagmo/algorithms/nsga2.hpp>
#include <pagmo/problems/dtlz.hpp>

using namespace pagmo;

int main()
{
    // 1 - Instantiate a pagmo problem constructing it from a UDP
    // (user defined problem).
    problem prob{dtlz(1, 10, 2)};

    // 2 - Instantiate a pagmo algorithm
    algorithm algo{nsga2(100)};

    // 3 - Instantiate a population
    population pop{prob, 24};

    // 4 - Evolve the population
    pop = algo.evolve(pop);

    // 5 - Output the population
    print("The population: \n", pop);
}

**Comment by bluescarni** [comment]
> Is this a good way to ask for help?

Opening issue reports is ok if you think there might be some issues/deficiencies with pagmo. We encourage users to come over to our gitter channel for more general-purpose questions/queries:

https://gitter.im/pagmo2/Lobby

>  We are starting a new research project and we are considering to extend Pagmo2, but we find the documentation a bit too sparse.

We put a lot of effort in thorough API documentation and testing, but I agree that our tutorials/introductions are lacking (especially on the C++ side, for Python the situation is a bit better). It's mostly down to a lack of manpower (as usual) and development prioritization, but we definitely have plans for better docs - and PRs are most welcome as usual :)

**Comment by MLopez-Ibanez** [comment]
Thanks for all the info. Would you be happy with a PR adding the above example to https://esa.github.io/pagmo2/quickstart.html ?

**Comment by darioizzo** [comment]
The quickstart shows how to call in parallel 16 evolutions using ```sade```. I think its a good example to start with pagmo since it includes a parallel setup. I think what you are missing are c++ tutorials. In particular the example above which shows the use with no multithreading of an algoritmic evolution. 

These tutorials can go in a dedicated section "C++ tutorials" to be added just above the "python tutorials"  link in the home page.

A PR is welcomed to add such a section on the documentation and start with a tutorial using and describing the code above. See the python tutorials for inspiration on a structure, I would say this would go in a section (basics) ....
