### ISSUE TITLE
Check parallel

### ISSUE THREAD

**Issue by ir1979** [esa/pagmo2#341]
I have built pagmo2 on windows 10 using VS 2017 using the following command:

`cmake ../ -G "Visual Studio 15 2017 Win64" -DTBB_ROOT="J:/Apps/TBB/tbb" -DCMAKE_CL_64=1 -DPAGMO_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX="J:\Program Files\EA" -DBoost_INCLUDE_DIR="J:/boost_1_70_0"  -DEIGEN3_INCLUDE_DIR="j:/Apps" -DPAGMO_WITH_EIGEN3=ON -DPAGMO_BUILD_TUTORIALS=ON`

cmake results:

```
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
-- The CXX compiler identification is MSVC 19.16.27030.1
-- The C compiler identification is MSVC 19.16.27030.1
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- System name: Windows
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include sys/wait.h
-- Looking for C++ include sys/wait.h - not found
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - not found
-- Looking for fork
-- Looking for fork - not found
-- The fork_island UDI will NOT be available.
-- '/W4': debug flag is supported by the compiler, enabling.
-- '/WX': debug flag is supported by the compiler, enabling.
-- The C++ compiler ID is: MSVC
-- YACMA autodetected C++ flags:
-- YACMA autodetected C++ debug flags: /W4;/WX
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Thread library:
-- The 'thread_local' keyword is supported.
CMake Warning (dev) at CMakeLists.txt:112 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable TBB_ROOT is set to:

    J:/Apps/TBB/tbb

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

I am not sure if pagmo algorithms can run in parallel mode (use all cores of my CPU). How can I test it?

**Comment by bluescarni** [comment]
@ir1979 everything looks in order, there's only a CMake warning about the use of the ``TBB_ROOT`` variable. If you can compile and run the test suite, then everything is ok (the test suite exercises some parallel capabilities).

**Comment by ir1979** [comment]
> @ir1979 everything looks in order, there's only a CMake warning about the use of the `TBB_ROOT` variable. If you can compile and run the test suite, then everything is ok (the test suite exercises some parallel capabilities).

But my CPU usage on my own problem shows that it uses only one CPU core! Is there any header file or library to be included?

**Comment by bluescarni** [comment]
pagmo does parallelisation in 2 ways:

* a coarse-grained parallelisation, in which you are running multiple separate optimisations in parallel via the ``archipelago`` class,
* a finer-grained parallelisation, in which you are running a single optimisation with an algorithm capable of taking advantage of parallel hardware.

The second type of parallelisation is something we added recently and it is supported so far only by a handful of algorithms. Could you provide some details on what you are trying to do?

**Comment by ir1979** [comment]
I believe EAs are a good place to exploit the power of parallel processing since the population evaluations (to the best of my knowledge) are independent procedures. however, I am new to pagmo2, I have an ordering problem (somehow similar to the famous TSP) and want to run it in parallel. Would you please provide me the links for the above  approaches for parallelization. Thaks.

**Comment by bluescarni** [comment]
> I believe EAs provide a good place to exploit the power of parallel processing since the population evaluations (to the best of my knowledge) are independent procedures

You are 100% right. However, parallelisation within an individual algorithm (which we refer to as *fine-grained* parallelisation) is something we have tackled only recently and thus it is available at the moment only in the NSGA2 and Ant Colony (GACO) algorithms. We plan to add more parallelised algorithms soon. If you are ok with using NSGA2/GACO at this time, you can find an example of fine-grained parallelisation in the GACO test suite:

https://github.com/esa/pagmo2/blob/master/tests/gaco.cpp#L337

(I encourage you to come over to our gitter channel if you have specific questions about how to use pagmo, it's easier to have a discussion there rather than in the github issue pages: https://gitter.im/pagmo2/Lobby )

On the other hand, the traditional parallelisation scheme adopted in pagmo is *coarse-grained* and based on the archipelago class. The basic idea is that you are running multiple separate optimisations in parallel, and if you throw migration in the mix you have something like an EA on steroids that uses the information flow between the optimisation processes to improve convergence.

A usage example for the archipelago class is here:

https://github.com/esa/pagmo2/blob/master/tutorials/getting_started.cpp

Again, please don't hesitate to come over to the gitter channel and talk to us. We are working on improving the user docs, which we are aware they are currently lacking.
