### ISSUE TITLE
Island removal from archipelagos

### ISSUE THREAD

**Issue by CoolRunning** [esa/pagmo2#400]
Currently, islands can be added to an archipelago by the `push_back` method. However, it is currently not possible to "remove" islands again.

There are some unsatisfying workarounds for the problem of removing island `i` from the archipelago, like creating a new archipelago and pushing all other islands there. If one simply wants to "reset" an island, its population can also be newly set.

It would be cleaner to be able to actually remove islands from the archipelago though. For this, some semantic questions need to be clarified (with regards to the migration log and migration database). Moreover, one would need

* extension of the topology API 
* actual support for removing islands from archipelagos

One simple proposal for the topology API would be to simply provide a method that removes the node of the island and all related connections from the Graph. Care needs to be taken also here with indexing to avoid confusion with features like the migration log and the migration database.

**Comment by bluescarni** [comment]
I spent some time looking at the archipelago code, and I think it should not be too difficult to implement.

The topology API extension should probably be optional, meaning that if an ``erase_vertex()`` (say) method is implemented in a UDT, then we can support islands removal in the archipelago, otherwise an error will be raised.

There are some questions regarding what should actually happen when you remove an island. For instance:

* should the topology just erase the existing vertex and its connections, or should it try to maintain its properties as-if it was produced by a sequence of ``push_back()`` calls? In concrete terms, if you remove a vertex from a ring, should it still be a ring or should it just be a partial ring with an interruption where the vertex was removed? The former option is nicer but it places an implementation burden on each UDT, the second option is more or less trivial to implement.
* What should happen to the migration log? Should we erase any reference in it to the island that has been removed? Should we alter the indices of the islands involved in a migration event in the log to take into account that an island index was removed (i.e., all islands with index ``idx > n`` should now have an index equal to ``idx - 1`` in the log)?

A secondary question mark for me is the fact that this feature might potentially send us down the path of a much more complicated archipelago manipulation API wrt what we have now. For instance, after this feature is implemented, we'd have ``push_back()`` and ``erase()`` for islands, but what about, for instance, adding islands at specified indices (i.e., an ``insert()`` method)? Should we ever consider implementing that, for symmetry with ``erase()``? This would also affect topologies, migration log, etc.

(Note that this last one is more of a vague concern at this time, I don't mean to be negative about the feature proposed here - just trying to foresee possible impact on future development)

**Comment by CoolRunning** [comment]
> * should the topology just erase the existing vertex and its connections, or should it try to maintain its properties as-if it was produced by a sequence of `push_back()` calls? In concrete terms, if you remove a vertex from a ring, should it still be a ring or should it just be a partial ring with an interruption where the vertex was removed? The former option is nicer but it places an implementation burden on each UDT, the second option is more or less trivial to implement.

I would suggest something like this:
Assume an archipelago `archi` with a custom topology `t`. Current behavior:
```
archi.push_back(isl)
```
will call `t.push_back()` to update the topology reflecting the state of the archipelago. Now I would propose
```
archi.pop(k)
```
to remove island `k` from `archi` to call a method `pop(k)` on `t` to reflect these changes. The `pop` method on the topology is optional: if it is not implemented, the standard behavior is to remove just vertex `k` with all its connections (i.e. this would break the ring). If the method `pop(k)` exists, it will be called instead. In the case of the ring, this could easily repair it by connecting vertices `k-1` to `k+1`, modulo `N`. 

> * What should happen to the migration log? Should we erase any reference in it to the island that has been removed? Should we alter the indices of the islands involved in a migration event in the log to take into account that an island index was removed (i.e., all islands with index `idx > n` should now have an index equal to `idx - 1` in the log)?

This is a more tricky issue and I have no good idea on it yet. I think, I would prefer to have some form of unique identifiers for each island, so history does not need to be "rewritten" if one island drops. This way, the island with the UID `xyz` would still be `xyz` no matter if it is at index 0 or 33 in an archipelago. Introducing this UID might have some ramifications though that I am not aware of.
An alternative is to let the user keep track of this, meaning that the migration log reflects the migration that happened at that time with those island at those specific indices of the archipelago. Imagining a very long migration log with a highly dynamic topology, this would be very painful though on the user.

> A secondary question mark for me is the fact that this feature might potentially send us down the path of a much more complicated archipelago manipulation API wrt what we have now. For instance, after this feature is implemented, we'd have `push_back()` and `erase()` for islands, but what about, for instance, adding islands at specified indices (i.e., an `insert()` method)? Should we ever consider implementing that, for symmetry with `erase()`? This would also affect topologies, migration log, etc.
 
> (Note that this last one is more of a vague concern at this time, I don't mean to be negative about the feature proposed here - just trying to foresee possible impact on future development)

I get your point. Obviously it is hard to say what the future will hold, but crazy ideas in my mind would involve merging and separating of whole archipelagos. I would love to do:
```
archi1, archi2 = archi[:k], archi[k:]
```
or
```
archi = archi1 + archi2
```
To a certain degree this would be possible by adjusting the topology accordingly, i.e. having `archi1` and `archi2` as isolated subgraphs in the topology. However, evolving them independently would be more difficult (but not impossible). So I would like - for the future - the archipelago assembly to be less rigid and more flexible. This would encourage research, but would complicate things a lot for "production" environments, where these experimental features are most likely not as relevant.

**Comment by bluescarni** [comment]
> I would suggest something like this:
> Assume an archipelago `archi` with a custom topology `t`. Current behavior:
> 
> ```
> archi.push_back(isl)
> ```
> 
> will call `t.push_back()` to update the topology reflecting the state of the archipelago. Now I would propose
> 
> ```
> archi.pop(k)
> ```
> 
> to remove island `k` from `archi` to call a method `pop(k)` on `t` to reflect these changes. The `pop` method on the topology is optional: if it is not implemented, the standard behavior is to remove just vertex `k` with all its connections (i.e. this would break the ring). If the method `pop(k)` exists, it will be called instead. In the case of the ring, this could easily repair it by connecting vertices `k-1` to `k+1`, modulo `N`.

Yep this is what I had in mind as well. Keep in mind however that, differently from pagmo 1.x, the topologies are not guaranteed to contain a graph. Some of them do (such as the ring topology), some do not (e.g., the fully connected topology does not store any graph data as it is trivial to construct a list of connections for each island on the fly, without having to store a memory-expensive O(n^2) data structure). So the "default" implementation of a ``pop()`` method would have to raise an error.

> This is a more tricky issue and I have no good idea on it yet. I think, I would prefer to have some form of unique identifiers for each island, so history does not need to be "rewritten" if one island drops. This way, the island with the UID `xyz` would still be `xyz` no matter if it is at index 0 or 33 in an archipelago. Introducing this UID might have some ramifications though that I am not aware of.
> An alternative is to let the user keep track of this, meaning that the migration log reflects the migration that happened at that time with those island at those specific indices of the archipelago. Imagining a very long migration log with a highly dynamic topology, this would be very painful though on the user.

Adding an ID to the islands is definitely a nice idea. There is one implementation of this idea which would be very easy to do, namely we could just take the memory address of the island object and convert it to an integral value (the same way the Python ``id()`` function works). This would allow us to avoid having to add an ID member to the island, and it also ensures that all existing islands have a different ID (as they are different C++ objects). The only downside would be that, depending on how the operating system handles memory allocations, it might be relatively easy to have duplicate IDs once you start constructing and destroying islands frequently (as the OS might decide to recycle previous memory allocations instead of allocating new memory).

> I get your point. Obviously it is hard to say what the future will hold, but crazy ideas in my mind would involve merging and separating of whole archipelagos. I would love to do:
> 
> ```
> archi1, archi2 = archi[:k], archi[k:]
> ```
> 
> or
> 
> ```
> archi = archi1 + archi2
> ```
> 
> To a certain degree this is already (almost) possible by adjusting the topology accordingly, i.e. having `archi1` and `archi2` as isolated subgraphs in the topology. However, evolving them independently would be more difficult (but not impossible). So I would like - for the future - the archipelago assembly to be less rigid and more flexible. This would encourage research, but would complicate things a lot for "production" environments, where these experimental features are most likely not as relevant.

I thought about the archipelago slicing and I think we could introduce in Python a ``sub_archipelago`` class which is created when you slice an archipelago. This class would just contain a list of references to the existing islands in an archipelago and it would expose an ``evolve()`` that just calls ``evolve()`` on each island object, thus triggering an evolution only on the islands listed in the ``sub_archipelago``. The islands would still be migrating to/from all the islands in the archipelago (and not only to/from the islands in the sub archipelago). Is that would you wanted or would you also like migration to be confined to the islands in the sub archi? That would also be perhaps doable but more complex.

**Comment by CoolRunning** [comment]
Whoops! I messed up and edited your reply instead of making my own. Did not even know I could do that?!

Sorry!

**Comment by bluescarni** [comment]
So I thought about island removal a bit more, and it came to me that there is a fundamental problem in Python (and that's one of the reasons island removal was not implemented in the first place, now that I remember):

```code ipython
>>> archi = archipelago(....)
>>> isl = archi[0]
>>> archi.pop(0)
>>> isl # <-- boom
```

In other words, when we remove an island from the archipelago via a pop(0) C++ function, Python will have no knowledge that the island at index 0, which is referenced also by the variable isl, has been destroyed. If this was pure Python, doing archi.pop(0) would not actually destroy the island object as long as isl exists, but there's no way of linking the lifetime of the island within the archipelago to the lifetime of isl.

I don't see any easy solution to solve this problem...

**Comment by bluescarni** [comment]
I will close this issue for now, as it is pretty clear that the way forward is to have an algebra on immutable (or only growable, rather) archipelagos.
