### ISSUE TITLE
Help!! Need Help with Gradient calculation.

### ISSUE THREAD

**Issue by A5troB0y** [esa/pagmo2#497]
Hi, i am new to optimization and pagmo, i am struggling with gradient calculation for IPOPT algorithm. As pagmo documentation doesn't have any examples it would help if someone could share some example codes with gradient functions.

**Comment by bluescarni** [comment]
@A5troB0y in order to provide a gradient, an optimisation problem must implement the ``gradient()`` member function as specified in the C++ docs:

https://esa.github.io/pagmo2/docs/cpp/problem.html#_CPPv4NK5pagmo7problem8gradientERK13vector_double

See here a concrete example for the Rosenbrock problem:

https://github.com/esa/pagmo2/blob/1fb2448cda6851f70076a947c84584a68d0b5187/src/problems/rosenbrock.cpp

**Comment by dinesh286** [comment]
@bluescarni Can your give example code for the functions given below

vector_double pagmo::estimate_gradient(Func f, const vector_double &x, double dx = 1e-8)
vector_double pagmo::estimate_gradient_h(Func f, const vector_double &x, double dx = 1e-2)
sparsity_pattern pagmo::estimate_sparsity(Func f, const vector_double &x, double dx = 1e-8)

The has to be used for a large scale optimization problem, proposed solvers are ipopt and nlopt.  There are clear examples available in pygmo2 to estimate gradient.  It works very well for IPOPT

**Comment by A5troB0y** [comment]
@bluescarni Hi, can you share some examples with estimate_gradient, estimate_gradient_h, the above example is calculating it directly in the gradient function itself.

**Comment by A5troB0y** [comment]
Gradient Calculation :

vector_double gradient(const vector_double &dv) const
    {
        return estimate_gradient([this](const vector_double &x) {return this->fitness(x);},dv);
    }
